name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 30
    permissions:
      contents: read
    defaults:
      run:
        working-directory: src-tauri
    steps:
      # actions/checkout@v4.1.7
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Lint
        run: cargo clippy --all-targets --locked -- -D warnings

      - name: Unit tests
        run: cargo test --locked
